name: walletapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # walletapp - hive database
  hive: any
  hive_flutter: any
  uuid: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # walletapp - flutter builder
  hive_generator: any
  build_runner: any

flutter:
  uses-material-design: true
